const sb=window.supabaseClient;let allProducts=[];let activeCat='';
const demo=[{id:'demo-1',name:'Màn hình iPhone 14 Pro Max OLED',category:'Màn hình',price:1850000,stock:8,image_url:'',shop:'Demo Marketplace',condition:'new'},{id:'demo-2',name:'JCID Programmer - bộ dụng cụ kỹ thuật',category:'Dụng cụ',price:3200000,stock:3,image_url:'',shop:'Demo Marketplace',condition:'new'},{id:'demo-3',name:'Pin iPhone 13 dung lượng cao',category:'Pin',price:390000,stock:15,image_url:'',shop:'Demo Marketplace',condition:'new'},{id:'demo-4',name:'IC nguồn iPhone - hàng tháo máy',category:'IC',price:680000,stock:5,image_url:'',shop:'Demo Marketplace',condition:'used'}];
function money(v){return new Intl.NumberFormat('vi-VN').format(Number(v||0))+' ₫'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(list){const g=document.getElementById('productGrid');document.getElementById('resultCount').textContent=' · '+list.length+' sản phẩm';if(!list.length){g.innerHTML='<div class="empty">Chưa có sản phẩm phù hợp.</div>';return}g.innerHTML=list.map(p=>'<article class="card"><div class="pic">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="'+esc(p.name)+'">':'🛍️')+'</div><div class="card-body"><span class="tag">'+esc(p.category)+'</span><div class="name">'+esc(p.name)+'</div><div class="price">'+money(p.price)+'</div><div class="shop">🏪 '+esc(p.shop||'Gian hàng Apple Seed')+' · Còn '+esc(p.stock)+'</div></div></article>').join('')}
function apply(){const q=document.getElementById('searchInput').value.trim().toLowerCase();let list=allProducts.filter(p=>(!activeCat||p.category===activeCat)&&(!q||[p.name,p.category,p.brand,p.model,p.shop].join(' ').toLowerCase().includes(q)));const s=document.getElementById('sort').value;if(s==='priceAsc')list.sort((a,b)=>a.price-b.price);if(s==='priceDesc')list.sort((a,b)=>b.price-a.price);if(s==='new')list.sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0));render(list)}
async function load(){if(!sb){allProducts=demo;apply();return}const r=await sb.from('marketplace_products').select('id,name,category,price,stock,image_url,condition,brand,model,created_at,marketplace_shops(shop_name)').eq('status','active').order('created_at',{ascending:false}).limit(60);if(r.error){console.warn('Marketplace:',r.error);allProducts=demo}else allProducts=(r.data||[]).map(p=>({...p,shop:p.marketplace_shops?.shop_name}));if(!allProducts.length)allProducts=demo;apply()}
function openModal(){document.getElementById('sellerModal').classList.add('open');document.getElementById('sellerModal').setAttribute('aria-hidden','false')}
function closeModal(){document.getElementById('sellerModal').classList.remove('open');document.getElementById('sellerModal').setAttribute('aria-hidden','true')}
async function createShop(){const msg=document.getElementById('sellerMsg');msg.textContent='';if(!sb){msg.textContent='Chưa kết nối Supabase.';return}const session=(await sb.auth.getSession()).data?.session;if(!session){msg.textContent='Vui lòng đăng nhập Member trước.';return}const name=document.getElementById('shopName').value.trim(),slug=document.getElementById('shopSlug').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,''),description=document.getElementById('shopDesc').value.trim(),phone=document.getElementById('shopPhone').value.trim();if(!name||!slug){msg.textContent='Nhập tên gian hàng và slug.';return}const r=await sb.from('marketplace_shops').insert({owner_id:session.user.id,shop_name:name,slug,description,phone,status:'pending'});if(r.error){msg.textContent='Không tạo được gian hàng: '+r.error.message;return}msg.textContent='Đã gửi gian hàng. Chờ Admin duyệt trước khi bán.'}
document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.cat;apply()});
document.getElementById('searchInput').oninput=apply;document.getElementById('sort').onchange=apply;document.getElementById('searchBtn').onclick=apply;
document.getElementById('openSeller').onclick=openModal;document.getElementById('openSeller2').onclick=openModal;document.getElementById('closeSeller').onclick=closeModal;
document.getElementById('sellerModal').onclick=e=>{if(e.target.id==='sellerModal')closeModal()};document.getElementById('createShop').onclick=createShop;load();