-- Apple Seed Member Management V1
-- Trial 3 days + member wallet/coins + payment proof + admin controls.
-- Separate migration: safe to rollback independently.

create table if not exists public.member_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  coins bigint not null default 0 check (coins >= 0),
  status text not null default 'trial'
    check (status in ('trial','active','expired','suspended')),
  trial_started_at timestamptz not null default now(),
  trial_expires_at timestamptz not null default (now() + interval '3 days'),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists member_accounts_status_idx on public.member_accounts(status);
create index if not exists member_accounts_trial_expires_idx on public.member_accounts(trial_expires_at);

create table if not exists public.member_payment_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  amount_vnd numeric(14,0) not null default 0 check (amount_vnd >= 0),
  requested_coins bigint not null default 0 check (requested_coins >= 0),
  bank_name text not null default 'MB Bank',
  bank_account text not null default '0898888269',
  account_holder text not null default 'Tô Thanh Trung',
  transfer_reference text not null default '',
  proof_path text,
  note text not null default '',
  status text not null default 'pending'
    check (status in ('pending','approved','rejected','cancelled')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  rejection_reason text not null default ''
);

create index if not exists member_payment_requests_user_idx
  on public.member_payment_requests(user_id, submitted_at desc);
create index if not exists member_payment_requests_status_idx
  on public.member_payment_requests(status, submitted_at desc);

create table if not exists public.member_coin_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delta bigint not null,
  balance_after bigint not null,
  transaction_type text not null
    check (transaction_type in ('admin_credit','admin_debit','payment_credit','usage','adjustment')),
  payment_request_id uuid references public.member_payment_requests(id) on delete set null,
  note text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists member_coin_ledger_user_idx
  on public.member_coin_ledger(user_id, created_at desc);

create or replace function public.apple_seed_create_member_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.member_accounts(user_id, trial_started_at, trial_expires_at)
  values (new.id, coalesce(new.created_at, now()), coalesce(new.created_at, now()) + interval '3 days')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_member_account on auth.users;
create trigger on_auth_user_created_member_account
after insert on auth.users
for each row execute function public.apple_seed_create_member_account();

insert into public.member_accounts(user_id, trial_started_at, trial_expires_at, created_at, updated_at)
select u.id, u.created_at, u.created_at + interval '3 days', coalesce(u.created_at,now()), now()
from auth.users u
on conflict (user_id) do nothing;

alter table public.member_accounts enable row level security;
alter table public.member_payment_requests enable row level security;
alter table public.member_coin_ledger enable row level security;

revoke all on table public.member_accounts from anon, authenticated;
revoke all on table public.member_payment_requests from anon, authenticated;
revoke all on table public.member_coin_ledger from anon, authenticated;

grant select on table public.member_accounts to authenticated;
grant select, insert on table public.member_payment_requests to authenticated;
grant select on table public.member_coin_ledger to authenticated;

drop policy if exists member_accounts_self_select on public.member_accounts;
create policy member_accounts_self_select
on public.member_accounts for select to authenticated
using (auth.uid() = user_id or public.apple_seed_is_admin());

drop policy if exists member_payment_self_select on public.member_payment_requests;
create policy member_payment_self_select
on public.member_payment_requests for select to authenticated
using (auth.uid() = user_id or public.apple_seed_is_admin());

drop policy if exists member_payment_self_insert on public.member_payment_requests;
create policy member_payment_self_insert
on public.member_payment_requests for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists member_payment_admin_all on public.member_payment_requests;
create policy member_payment_admin_all
on public.member_payment_requests for all to authenticated
using (public.apple_seed_is_admin())
with check (public.apple_seed_is_admin());

drop policy if exists member_ledger_self_select on public.member_coin_ledger;
create policy member_ledger_self_select
on public.member_coin_ledger for select to authenticated
using (auth.uid() = user_id or public.apple_seed_is_admin());

-- Keep direct wallet writes out of the browser. Coin changes go through the admin RPC below.
drop policy if exists member_accounts_admin_all on public.member_accounts;
create policy member_accounts_admin_all
on public.member_accounts for all to authenticated
using (public.apple_seed_is_admin())
with check (public.apple_seed_is_admin());

drop policy if exists member_ledger_admin_all on public.member_coin_ledger;
create policy member_ledger_admin_all
on public.member_coin_ledger for all to authenticated
using (public.apple_seed_is_admin())
with check (public.apple_seed_is_admin());

-- Admin-only member list. Reads auth.users server-side without exposing auth schema to the browser.
create or replace function public.apple_seed_admin_member_list(
  p_search text default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns table (
  user_id uuid,
  email text,
  email_confirmed_at timestamptz,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  full_name text,
  phone text,
  account_status text,
  coins bigint,
  trial_started_at timestamptz,
  trial_expires_at timestamptz,
  last_seen_at timestamptz,
  pending_payments bigint
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.apple_seed_is_admin() then
    raise exception 'Admin only';
  end if;

  return query
  select
    u.id,
    u.email::text,
    u.email_confirmed_at,
    u.created_at,
    u.last_sign_in_at,
    coalesce(cm.full_name, u.raw_user_meta_data->>'full_name')::text,
    coalesce(cm.phone, u.raw_user_meta_data->>'phone')::text,
    coalesce(ma.status,
      case when coalesce(ma.trial_expires_at, u.created_at + interval '3 days') > now()
        then 'trial' else 'expired' end)::text,
    coalesce(ma.coins,0)::bigint,
    coalesce(ma.trial_started_at,u.created_at),
    coalesce(ma.trial_expires_at,u.created_at + interval '3 days'),
    ma.last_seen_at,
    (select count(*) from public.member_payment_requests pr
      where pr.user_id=u.id and pr.status='pending')::bigint
  from auth.users u
  left join public.customer_members cm on cm.user_id=u.id
  left join public.member_accounts ma on ma.user_id=u.id
  where (
    nullif(trim(coalesce(p_search,'')),'') is null
    or lower(coalesce(u.email,'')) like '%'||lower(trim(p_search))||'%'
    or lower(coalesce(cm.full_name,u.raw_user_meta_data->>'full_name','')) like '%'||lower(trim(p_search))||'%'
    or coalesce(cm.phone,u.raw_user_meta_data->>'phone','') like '%'||trim(p_search)||'%'
  )
  order by u.created_at desc
  limit greatest(1,least(coalesce(p_limit,100),500))
  offset greatest(coalesce(p_offset,0),0);
end;
$$;

revoke all on function public.apple_seed_admin_member_list(text,integer,integer) from public, anon, authenticated;
grant execute on function public.apple_seed_admin_member_list(text,integer,integer) to authenticated;

create or replace function public.apple_seed_admin_member_detail(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  result jsonb;
begin
  if not public.apple_seed_is_admin() then
    raise exception 'Admin only';
  end if;
  if p_user_id is null then raise exception 'Missing user id'; end if;

  select jsonb_build_object(
    'account', jsonb_build_object(
      'user_id', u.id,
      'email', u.email,
      'email_confirmed_at', u.email_confirmed_at,
      'created_at', u.created_at,
      'last_sign_in_at', u.last_sign_in_at,
      'phone_auth', u.phone,
      'full_name', coalesce(cm.full_name,u.raw_user_meta_data->>'full_name'),
      'phone', coalesce(cm.phone,u.raw_user_meta_data->>'phone'),
      'status', coalesce(ma.status, case when coalesce(ma.trial_expires_at,u.created_at+interval '3 days')>now() then 'trial' else 'expired' end),
      'coins', coalesce(ma.coins,0),
      'trial_started_at', coalesce(ma.trial_started_at,u.created_at),
      'trial_expires_at', coalesce(ma.trial_expires_at,u.created_at+interval '3 days'),
      'last_seen_at', ma.last_seen_at
    ),
    'payments', coalesce((
      select jsonb_agg(to_jsonb(pr) order by pr.submitted_at desc)
      from public.member_payment_requests pr where pr.user_id=u.id
    ), '[]'::jsonb),
    'ledger', coalesce((
      select jsonb_agg(to_jsonb(l) order by l.created_at desc)
      from public.member_coin_ledger l where l.user_id=u.id
    ), '[]'::jsonb)
  )
  into result
  from auth.users u
  left join public.customer_members cm on cm.user_id=u.id
  left join public.member_accounts ma on ma.user_id=u.id
  where u.id=p_user_id;

  if result is null then raise exception 'Member not found'; end if;
  return result;
end;
$$;

revoke all on function public.apple_seed_admin_member_detail(uuid) from public, anon, authenticated;
grant execute on function public.apple_seed_admin_member_detail(uuid) to authenticated;

create or replace function public.apple_seed_admin_credit_coins(
  p_user_id uuid,
  p_delta bigint,
  p_note text default '',
  p_payment_request_id uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_balance bigint;
  old_status text;
begin
  if not public.apple_seed_is_admin() then raise exception 'Admin only'; end if;
  if p_user_id is null then raise exception 'Missing user id'; end if;
  if coalesce(p_delta,0) <= 0 then raise exception 'Coin credit must be greater than zero'; end if;

  if p_payment_request_id is not null then
    if not exists (
      select 1 from public.member_payment_requests
      where id=p_payment_request_id and user_id=p_user_id and status='pending'
    ) then
      raise exception 'Payment request is not pending or does not belong to this member';
    end if;
  end if;

  insert into public.member_accounts(user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select coins,status into new_balance,old_status
  from public.member_accounts
  where user_id=p_user_id
  for update;

  new_balance := coalesce(new_balance,0) + p_delta;

  update public.member_accounts
  set coins=new_balance,
      status=case when old_status='suspended' then 'suspended' else 'active' end,
      updated_at=now()
  where user_id=p_user_id;

  insert into public.member_coin_ledger(user_id,delta,balance_after,transaction_type,payment_request_id,note,created_by)
  values (p_user_id,p_delta,new_balance,
    case when p_payment_request_id is null then 'admin_credit' else 'payment_credit' end,
    p_payment_request_id,coalesce(p_note,''),auth.uid());

  if p_payment_request_id is not null then
    update public.member_payment_requests
    set status='approved', reviewed_at=now(), reviewed_by=auth.uid()
    where id=p_payment_request_id and status='pending';
  end if;

  return new_balance;
end;
$$;

revoke all on function public.apple_seed_admin_credit_coins(uuid,bigint,text,uuid) from public, anon, authenticated;
grant execute on function public.apple_seed_admin_credit_coins(uuid,bigint,text,uuid) to authenticated;

create or replace function public.apple_seed_admin_set_member_status(
  p_user_id uuid,
  p_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.apple_seed_is_admin() then raise exception 'Admin only'; end if;
  if p_status not in ('trial','active','expired','suspended') then raise exception 'Invalid member status'; end if;
  insert into public.member_accounts(user_id) values(p_user_id) on conflict(user_id) do nothing;
  update public.member_accounts set status=p_status, updated_at=now() where user_id=p_user_id;
  return found;
end;
$$;

revoke all on function public.apple_seed_admin_set_member_status(uuid,text) from public, anon, authenticated;
grant execute on function public.apple_seed_admin_set_member_status(uuid,text) to authenticated;

create or replace function public.apple_seed_member_touch()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then return false; end if;
  insert into public.member_accounts(user_id) values(auth.uid()) on conflict(user_id) do nothing;
  update public.member_accounts
  set last_seen_at=now(), updated_at=now()
  where user_id=auth.uid();
  return true;
end;
$$;

revoke all on function public.apple_seed_member_touch() from public, anon;
grant execute on function public.apple_seed_member_touch() to authenticated;

-- Private proof bucket. Actual file access is controlled by storage.objects RLS.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values (
  'member-payment-proofs',
  'member-payment-proofs',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set public=false,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists member_payment_proof_insert on storage.objects;
create policy member_payment_proof_insert
on storage.objects for insert to authenticated
with check (
  bucket_id='member-payment-proofs'
  and (storage.foldername(name))[1]=auth.uid()::text
  and lower(storage.extension(name)) in ('jpg','jpeg','png','webp')
);

drop policy if exists member_payment_proof_select_own on storage.objects;
create policy member_payment_proof_select_own
on storage.objects for select to authenticated
using (
  bucket_id='member-payment-proofs'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or public.apple_seed_is_admin()
  )
);

drop policy if exists member_payment_proof_delete_own on storage.objects;
create policy member_payment_proof_delete_own
on storage.objects for delete to authenticated
using (
  bucket_id='member-payment-proofs'
  and (
    (storage.foldername(name))[1]=auth.uid()::text
    or public.apple_seed_is_admin()
  )
);
