-- Apple Seed Stable Guard: website-wide code rollback
-- Migration name: stable_guard_website_rollback

create table if not exists public.stable_guard_snapshots (
  id bigint generated by default as identity primary key,
  repository text not null default 'Totrungtv/appleseed-website',
  branch text not null default 'main',
  commit_sha text not null,
  label text not null default 'Stable',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(repository, branch, commit_sha)
);

create index if not exists stable_guard_snapshots_created_at_idx
  on public.stable_guard_snapshots(created_at desc);

create table if not exists public.stable_guard_requests (
  id uuid primary key default gen_random_uuid(),
  snapshot_id bigint not null references public.stable_guard_snapshots(id) on delete restrict,
  requested_by uuid references auth.users(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending','processing','succeeded','failed','cancelled')),
  requested_at timestamptz not null default now(),
  processed_at timestamptz,
  result_commit_sha text,
  message text not null default '',
  error_message text not null default ''
);

create index if not exists stable_guard_requests_status_idx
  on public.stable_guard_requests(status, requested_at);

alter table public.stable_guard_snapshots enable row level security;
alter table public.stable_guard_requests enable row level security;

drop policy if exists stable_guard_snapshots_admin_select on public.stable_guard_snapshots;
create policy stable_guard_snapshots_admin_select
on public.stable_guard_snapshots for select to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists stable_guard_snapshots_admin_insert on public.stable_guard_snapshots;
create policy stable_guard_snapshots_admin_insert
on public.stable_guard_snapshots for insert to authenticated
with check (created_by = auth.uid() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists stable_guard_requests_admin_select on public.stable_guard_requests;
create policy stable_guard_requests_admin_select
on public.stable_guard_requests for select to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists stable_guard_requests_admin_insert on public.stable_guard_requests;
create policy stable_guard_requests_admin_insert
on public.stable_guard_requests for insert to authenticated
with check (requested_by = auth.uid() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists stable_guard_requests_admin_update on public.stable_guard_requests;
create policy stable_guard_requests_admin_update
on public.stable_guard_requests for update to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

create or replace function public.stable_guard_claim_request(p_worker text default 'github-actions')
returns table (request_id uuid, snapshot_id bigint, repository text, branch text, commit_sha text, label text)
language plpgsql security definer set search_path = public
as $$
begin
  return query
  with picked as (
    select r.id from public.stable_guard_requests r
    where r.status = 'pending'
    order by r.requested_at asc
    for update skip locked limit 1
  ),
  claimed as (
    update public.stable_guard_requests r
    set status = 'processing',
        message = case when r.message = '' then 'Claimed by ' || coalesce(p_worker,'worker') else r.message end
    from picked where r.id = picked.id
    returning r.id, r.snapshot_id
  )
  select c.id, s.id, s.repository, s.branch, s.commit_sha, s.label
  from claimed c join public.stable_guard_snapshots s on s.id = c.snapshot_id;
end;
$$;

create or replace function public.stable_guard_complete_request(
  p_request_id uuid, p_status text, p_result_commit_sha text default null,
  p_message text default '', p_error_message text default ''
)
returns boolean
language plpgsql security definer set search_path = public
as $$
begin
  if p_status not in ('succeeded','failed','cancelled') then raise exception 'Invalid stable guard status'; end if;
  update public.stable_guard_requests
  set status=p_status, processed_at=now(), result_commit_sha=p_result_commit_sha,
      message=coalesce(p_message,''), error_message=coalesce(p_error_message,'')
  where id=p_request_id and status='processing';
  return found;
end;
$$;

grant execute on function public.stable_guard_claim_request(text) to anon, authenticated;
grant execute on function public.stable_guard_complete_request(uuid,text,text,text,text) to anon, authenticated;


-- Worker authentication hardening
create table if not exists public.stable_guard_worker (
  id boolean primary key default true check (id),
  token_hash text not null,
  updated_at timestamptz not null default now()
);
alter table public.stable_guard_worker enable row level security;

-- The token hash is installed separately in the live database and must never be committed in plaintext.
-- GitHub Actions uses the STABLE_GUARD_WORKER_TOKEN repository secret.
-- Do not add the plaintext worker token to this SQL file.

drop function if exists public.stable_guard_claim_request(text);
drop function if exists public.stable_guard_complete_request(uuid,text,text,text,text);

create or replace function public.stable_guard_claim_request(p_worker_token text)
returns table (request_id uuid, snapshot_id bigint, repository text, branch text, commit_sha text, label text)
language plpgsql security definer set search_path = public
as $$
begin
  if not exists (
    select 1 from public.stable_guard_worker
    where id=true
      and token_hash=encode(digest(coalesce(p_worker_token,''),'sha256'),'hex')
  ) then
    raise exception 'Unauthorized worker';
  end if;

  return query
  with picked as (
    select r.id
    from public.stable_guard_requests r
    where r.status='pending'
    order by r.requested_at asc
    for update skip locked
    limit 1
  ),
  claimed as (
    update public.stable_guard_requests r
    set status='processing',
        message=case when r.message='' then 'Claimed by github-actions' else r.message end
    from picked
    where r.id=picked.id
    returning r.id,r.snapshot_id
  )
  select c.id,s.id,s.repository,s.branch,s.commit_sha,s.label
  from claimed c
  join public.stable_guard_snapshots s on s.id=c.snapshot_id;
end;
$$;

create or replace function public.stable_guard_complete_request(
  p_worker_token text,
  p_request_id uuid,
  p_status text,
  p_result_commit_sha text default null,
  p_message text default '',
  p_error_message text default ''
)
returns boolean
language plpgsql security definer set search_path = public
as $$
begin
  if not exists (
    select 1 from public.stable_guard_worker
    where id=true
      and token_hash=encode(digest(coalesce(p_worker_token,''),'sha256'),'hex')
  ) then
    raise exception 'Unauthorized worker';
  end if;

  if p_status not in ('succeeded','failed','cancelled') then
    raise exception 'Invalid stable guard status';
  end if;

  update public.stable_guard_requests
  set status=p_status,
      processed_at=now(),
      result_commit_sha=p_result_commit_sha,
      message=coalesce(p_message,''),
      error_message=coalesce(p_error_message,'')
  where id=p_request_id
    and status='processing';

  return found;
end;
$$;

grant execute on function public.stable_guard_claim_request(text) to anon;
grant execute on function public.stable_guard_complete_request(text,uuid,text,text,text,text) to anon;
revoke execute on function public.stable_guard_claim_request(text) from authenticated;
revoke execute on function public.stable_guard_complete_request(text,uuid,text,text,text,text) from authenticated;
