-- APPLE SEED - DATABASE QUẢN LÝ CỬA HÀNG
-- Chạy toàn bộ file này trong Supabase > SQL Editor.
-- Không xóa các bảng products/pages hiện có.

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  address text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.repair_orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete set null,
  device_model text not null,
  imei text,
  customer_issue text,
  device_condition text,
  technician text,
  estimated_total numeric(14,2) not null default 0,
  paid_amount numeric(14,2) not null default 0,
  status text not null default 'pending'
    check (status in ('pending','repairing','done','delivered','failed')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text,
  quantity integer not null default 0,
  cost_price numeric(14,2) not null default 0,
  sale_price numeric(14,2) not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income','expense')),
  amount numeric(14,2) not null default 0,
  description text not null,
  payment_method text,
  repair_order_id bigint references public.repair_orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_repair_orders_status on public.repair_orders(status);
create index if not exists idx_repair_orders_customer on public.repair_orders(customer_id);
create index if not exists idx_repair_orders_created on public.repair_orders(created_at desc);
create index if not exists idx_inventory_sku on public.inventory_items(sku);
create index if not exists idx_transactions_created on public.store_transactions(created_at desc);

alter table public.customers enable row level security;
alter table public.repair_orders enable row level security;
alter table public.inventory_items enable row level security;
alter table public.store_transactions enable row level security;

-- Admin đã đăng nhập Supabase mới được đọc/ghi dữ liệu.
drop policy if exists "authenticated customers all" on public.customers;
create policy "authenticated customers all" on public.customers
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated repairs all" on public.repair_orders;
create policy "authenticated repairs all" on public.repair_orders
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated inventory all" on public.inventory_items;
create policy "authenticated inventory all" on public.inventory_items
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated transactions all" on public.store_transactions;
create policy "authenticated transactions all" on public.store_transactions
for all to authenticated using (true) with check (true);

-- Cập nhật updated_at tự động
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_customers_updated_at on public.customers;
drop trigger if exists trg_repair_orders_updated_at on public.repair_orders;
drop trigger if exists trg_inventory_updated_at on public.inventory_items;

-- customers không có updated_at nên chỉ áp dụng cho 2 bảng có cột này.
create trigger trg_repair_orders_updated_at
before update on public.repair_orders
for each row execute function public.set_updated_at();

create trigger trg_inventory_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();
