-- Apple Seed AI Knowledge + Image Analysis V1
-- Applied migration: ai_knowledge_image_workspace_v1

create table if not exists public.ai_knowledge (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null default 'general',
  source_type text not null default 'admin',
  source_ref text,
  image_path text,
  image_url text,
  status text not null default 'draft' check (status in ('draft','approved','archived')),
  created_by uuid references auth.users(id) on delete set null,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ai_knowledge_status_idx on public.ai_knowledge(status);
create index if not exists ai_knowledge_category_idx on public.ai_knowledge(category);
create index if not exists ai_knowledge_updated_idx on public.ai_knowledge(updated_at desc);

alter table public.ai_knowledge enable row level security;

drop policy if exists "ai_knowledge_admin_read" on public.ai_knowledge;
create policy "ai_knowledge_admin_read" on public.ai_knowledge for select to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "ai_knowledge_admin_insert" on public.ai_knowledge;
create policy "ai_knowledge_admin_insert" on public.ai_knowledge for insert to authenticated
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') and created_by=auth.uid());

drop policy if exists "ai_knowledge_admin_update" on public.ai_knowledge;
create policy "ai_knowledge_admin_update" on public.ai_knowledge for update to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "ai_knowledge_admin_delete" on public.ai_knowledge;
create policy "ai_knowledge_admin_delete" on public.ai_knowledge for delete to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('ai-knowledge','ai-knowledge',false,8388608,array['image/jpeg','image/png','image/webp','image/gif','application/pdf','text/plain'])
on conflict (id) do update set file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types,public=excluded.public;

drop policy if exists "ai_knowledge_storage_read" on storage.objects;
create policy "ai_knowledge_storage_read" on storage.objects for select to authenticated
using (bucket_id='ai-knowledge' and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "ai_knowledge_storage_insert" on storage.objects;
create policy "ai_knowledge_storage_insert" on storage.objects for insert to authenticated
with check (bucket_id='ai-knowledge' and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "ai_knowledge_storage_update" on storage.objects;
create policy "ai_knowledge_storage_update" on storage.objects for update to authenticated
using (bucket_id='ai-knowledge' and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (bucket_id='ai-knowledge' and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "ai_knowledge_storage_delete" on storage.objects;
create policy "ai_knowledge_storage_delete" on storage.objects for delete to authenticated
using (bucket_id='ai-knowledge' and exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
