-- APPLE SEED CMS: chạy file này trong Supabase SQL Editor
-- 1) Tạo bảng trang động
create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text default '',
  content text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pages enable row level security;

drop policy if exists "pages_public_read" on public.pages;
create policy "pages_public_read"
on public.pages for select
to anon, authenticated
using (is_active = true);

drop policy if exists "pages_admin_read_all" on public.pages;
create policy "pages_admin_read_all"
on public.pages for select
to authenticated
using (true);

drop policy if exists "pages_admin_insert" on public.pages;
create policy "pages_admin_insert"
on public.pages for insert
to authenticated
with check (true);

drop policy if exists "pages_admin_update" on public.pages;
create policy "pages_admin_update"
on public.pages for update
to authenticated
using (true)
with check (true);

drop policy if exists "pages_admin_delete" on public.pages;
create policy "pages_admin_delete"
on public.pages for delete
to authenticated
using (true);

-- 2) Cho tài khoản đã đăng nhập quản lý products.
-- Public vẫn chỉ đọc sản phẩm đang hoạt động.
alter table public.products enable row level security;

drop policy if exists "products_public_read_active" on public.products;
create policy "products_public_read_active"
on public.products for select
to anon, authenticated
using (is_active = true);

drop policy if exists "products_admin_read_all" on public.products;
create policy "products_admin_read_all"
on public.products for select
to authenticated
using (true);

drop policy if exists "products_admin_insert" on public.products;
create policy "products_admin_insert"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "products_admin_update" on public.products;
create policy "products_admin_update"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "products_admin_delete" on public.products;
create policy "products_admin_delete"
on public.products for delete
to authenticated
using (true);

-- Lưu ý:
-- Đây là quyền cho BẤT KỲ tài khoản Supabase đã đăng nhập.
-- Sau khi chạy ổn, nếu muốn khóa chỉ cho riêng tài khoản ông,
-- ta sẽ đổi policy thành kiểm tra auth.uid() của tài khoản admin.
